name: CI
on:

  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:

  build:
    name: lint, build, and test
    runs-on: macos-latest
    permissions:
      contents: read
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, windows-latest, macos-latest]
    #  fail-fast: false  # Let all jobs run even if one fails

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install eiffel
        run: brew install eiffelstudio
        shell: bash
      - name: install actionlint
        shell: bash
        run: brew install actionlint
      - name: install checkmake
        shell: bash
        run: brew install checkmake
      - name:  lint the Makefile
        shell: bash
        run: time make lint.make
      - name: lint GitHub workflows
        shell: bash
        run: time make lint.workflows
      - name: build the application
        shell: bash
        run: time make build
      - name: run tests
        shell: bash
        run: time make test
